### PR TITLE
Support Instagram

### PR DESCRIPTION
**Pull request by elvisyjlin**
* Added the main page
   * Search bar
   * Results are displayed in cards
   * Download buttons
* Integrated with the api server
* Updated readme
* Added changelog and license

### CODE REVIEW

**Comment by tychiadet** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Valaia, @sperlzthewiz, @Earthnook, @Alpha2J, @triangulair, @defipunk, @tharunrai14, @JordanGallant, @mikakort, @xianz271828, @LorisGr, @lambertchu, @jungleninja, @ywmuazz, @masaki345, @edjanga, @polydeuces32, @d3kal3, @henrytirla, @waitkeeper, @cargo8, @jessdonohoe, @0xdef1, @Phantom0008, @divinikal, @togiter, @tomfurrier, @rogerRaak, @AlterNayte, @Wei-Jianan, @luotuo29, @abc0xmattyic333, @LarryStanley, @tuxcanfly, @dantech0xff, @trend2023, @eddie333016, @kun-g, @sunlei, @aminmalekzadeh, @JoKrk, @squidsuit0x, @physician, @CarstenNZ, @superwaih, @burubiu, @Nilotaviano, @jm42, @NickyMan56, @megaacheyounes

**Comment by GTMany** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
aphl3x91, @trinhher78, @mostafa365, @ftikhonin, @milestours, @chardso, @mohammadsalim123, @Aradfa27, @Rashaqama, @gwyxjtu, @Samuellyworld, @JuliGray, @cryptochel, @bardiyanft, @hado1990, @Mreth7704, @bno-githu, @esinndemiir, @vardi5028, @sarnyaia1, @Meneptah, @taharj, @cyberpunkthree, @wbfc, @Amin8770, @Diducm, @robocups, @1190200610, @Glowstudent777, @hosseinzar, @V0y4g3r2, @Leyaaryaei, @nora-mm, @aswini725, @llovelyll, @parvin610, @raminang, @bboyzmey666, @8936866519, @vahidhabibi, @m-quigley, @hassansomi, @jasonhoi, @Send2014, @mohammadjavad7, @aptimus3, @felipe-op, @ghostman54, @shilohma, @elpatroncrypto02

**Comment by ChrisBuckets** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Suherm, @lilpacy, @pariigh, @peterduhon, @christiananese, @Jessicazr86, @gzimh, @Nixon-Joseph, @wictor23, @NimaEagle, @jackiewu, @SkalskiP, @andrewda, @puffdood, @EverestJoo, @BJ-Dai, @Lylelljr, @faizhameed, @qjyoung, @Tomyxtrejo, @kingport, @enpro540, @yulodl, @RuzgarAtaOzkan, @eltonbfw, @evmKnight, @Romej, @fathi110, @MM25Zamanian, @codewithdpk, @attomos, @r4ym0n, @anonimusprogramus, @lequochung19971, @ShibaRiba, @Mai2537, @gabriel-del, @MarkTangCd, @virus231, @msadura, @SevenbitsHarshad, @DevenLu, @Pent, @Gemk83, @felixgouin, @anshu4sharma, @luckyJeffy, @perezkceres, @JuanMartinRivas, @EmmmaG

**Comment by chugo-admin** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Ardeshir-Shon, @meiwhu, @0xthierry, @msheahen, @nitish-mehta, @sabrina-k, @luo4lu, @plainfatboy, @DataCrusade1999, @8mmiv, @m4ns0ur, @SQDzhuzhuxia, @delans, @hongikeam, @keito-fukuda, @AnanthaRajuC, @nicholasjs, @deepanshuoct12, @thepirateboy, @santihugin, @FitzLu, @longxinH, @lambertchu, @wolf0931, @alieb1380, @Phantim97, @brunokiafuka, @aStudier, @mositori, @wesleysmyth, @filipepratalima, @dogagcmnr, @pyncz, @tzzzoz, @Devorein, @Atemndobs, @fobabs, @anothermayank, @longgeek, @108abhishek, @Desgard, @hridyansh68, @RirDRImOMa, @thekscar, @samirdjelal, @gsyndromes, @SamuraiT, @vanpersiexp, @dodadoa, @Appletone

**Pull request merged**
